### ISSUE TITLE
Styling needed

### ISSUE THREAD

**Issue by n1haldev** [n1haldev/project#4]
There is a need for css styling in Footer, FAQ and Contact Page.

**Comment by ndigvijay** [comment]
footer is over 
XD

**Comment by n1haldev** [comment]
Right.
But there is more styling needed on FAQ and Contact Page.

**Comment by nishanthdmello** [comment]
on it

**Comment by n1haldev** [comment]
enough styling has been done to the necessary pages and therefore I am closing this issue
